---
- hosts: localhost
  sudo: yes

  vars:
    redhat_java_packages:
      - java-1.8.0-openjdk-devel
    debian_java_packages:
      - openjdk-8-jdk
    redhat_python3_packages:
      - python34
    debian_python3_packages:
      - python34
    redhat_desktop: xfce
#TODO: cinnamon is not working

  tasks:

  - name: Install RedHat Python 3 packages
    yum: name={{ item }} state=latest
    with_items: redhat_python3_packages
    when: ansible_os_family == 'RedHat'

  - name: Install Debian Python 3 packages
    apt: name={{ item }} state=latest
    with_items: debian_python3_packages
    when: ansible_os_family == 'Debian'

  roles:
    - { role: ansible-dev-user-setup }
    - { role: redhat-smola.java }
    - { role: ansible-pip }
    - { role: ansible-linux-desktop }
    - { role: ansible-eclipse }
