---
- hosts: localhost
  sudo: yes

  roles:
  - { role: redhat-smola.java }
  - { role: ansible-pip }

  vars:
    redhat_java_packages:
      - java-1.8.0-openjdk-devel
    debian_java_packages:
      - openjdk-8-jdk
    redhat_python3_packages:
      - python34
    debian_python3_packages:
      - python34

  tasks:

  # Add odldev user in ODLDEV group and grant sudo permission
  - group: name=ODLDEV
  - user: name=odldev comment="ODL developer" uid=1010 group="ODLDEV" groups="wheel" shell=/bin/bash password=$6$rounds=656000$lL0xQ0LBywL04CXY$D4GxCJGv4P/dSpRkNJgUB/VB9XnXR94sOE9JTMuK189FrVhLbesixzhU0qfjuN3NihdH7YOs0RtsrhtEOGNey0

  - name: Install RedHat Python 3 packages
    yum: name={{ item }} state=latest
    with_items: redhat_python3_packages
    when: ansible_os_family == 'RedHat'

  - name: Install Debian Python 3 packages
    apt: name={{ item }} state=latest
    with_items: debian_python3_packages
    when: ansible_os_family == 'Debian'

