Vagrant.configure(2) do |config|
  config.vm.box = "opendaylight"

    config.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
        # Customize the amount of memory on the VM:
        vb.memory = "6144"
        vb.cpus = 4
        # Enable the shared clipboard:
        vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    end

end
